[relaychain]
default_command = "polkadot"
default_args = ["-lparachain=debug"]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[relaychain.nodes]]
name = "charlie"
validator = true

[[relaychain.nodes]]
name = "dave"
validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain = "contracts-rococo-local"

[parachains.collator]
name = "collator"
command = "polkadot-parachain"
args = ["-lparachain=debug"]
