[relaychain]
default_command = "`deno task capi bin polkadot v0.9.39-1`"
default_args = ["-lparachain=debug"]
chain = "polkadot-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[relaychain.nodes]]
name = "charlie"
validator = true

[[relaychain.nodes]]
name = "dave"
validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain = "statemine-local"

[parachains.collator]
name = "collator"
command = "`deno task capi bin polkadot-parachain v0.9.380`"
args = ["-lparachain=debug"]
