[settings]
timeout = 1000

[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
extra_args = ["-lparachain=debug"]

[[relaychain.nodes]]
name = "bob"
validator = true
extra_args = ["-lparachain=debug"]

[[relaychain.nodes]]
name = "charlie"
validator = true
extra_args = ["-lparachain=debug"]

[[parachains]]
id = 1000
cumulus_based = true
chain = "statemine-local"

[[parachains.collators]]
name = "statemine-collator01"
image = "docker.io/parity/polkadot-parachain:latest"
command = "polkadot-parachain"
args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 2000
cumulus_based = true

[[parachains.collators]]
name = "trappist-collator01"
image = "docker.io/parity/polkadot-parachain:latest"
command = "trappist-collator"
args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 3000
cumulus_based = true

[[parachains.collators]]
name = "stout-collator01"
image = "docker.io/parity/polkadot-parachain:latest"
command = "stout-collator"
args = ["--log=xcm=trace,pallet-assets=trace"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"

[[hrmp_channels]]
sender = 1000
recipient = 2000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2000
recipient = 1000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 1000
recipient = 3000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 3000
recipient = 1000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2000
recipient = 3000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 3000
recipient = 2000
max_capacity = 8
max_message_size = 512
