image:
  file: .gitpod.Dockerfile
tasks:
  - init: deno task star
vscode:
  extensions:
    - EditorConfig.EditorConfig
    - bungcip.better-toml
    - denoland.vscode-deno
    - dprint.dprint
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
    - streetsidesoftware.code-spell-checker
    - vadimcn.vscode-lldb
