image:
  file: Dockerfile
tasks:
  - init: deno task star
vscode:
  extensions:
    - DavidAnson.vscode-markdownlint
    - EditorConfig.EditorConfig
    - denoland.vscode-deno
    - dprint.dprint
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
    - streetsidesoftware.code-spell-checker
    - vadimcn.vscode-lldb
