[book]
title = "Capi Documentation"
src = "_docs"

[build]
build-dir = "target/mdbook"
create-missing = false

[output.html]
git-repository-url = "https://github.com/paritytech/capi"
# edit-url-template = "https://github.com/paritytech/capi/edit/main/{path}"
