// This file was generated by `_tasks/download_frame_metadata.ts`
import * as U from "../../util/mod.ts"
import { $metadata } from "../mod.ts"

export const [
  acala,
  kusama,
  moonbeam,
  polkadot,
  rococo,
  statemint,
  subsocial,
  westend,
] = await Promise.all([
  download("acala"),
  download("kusama"),
  download("moonbeam"),
  download("polkadot"),
  download("rococo"),
  download("statemint"),
  download("subsocial"),
  download("westend"),
])

async function download(name: string) {
  return $metadata.decode(
    U.hex.decodeBuf((await Deno.readFile(new URL(`./${name}.scale`, import.meta.url))).slice(2)),
  )
}
