// This file was generated by `_tasks/download.ts`
import { hex } from "../../util/mod.ts"
import { $metadata } from "../mod.ts"

export const [
  kusama,
  polkadot,
  westend,
  rococo,
] = await Promise.all([
  download("kusama"),
  download("polkadot"),
  download("westend"),
  download("rococo"),
])

async function download(name: string) {
  return $metadata.decode(
    hex.decodeBuf((await Deno.readFile(new URL(`./${name}.scale`, import.meta.url))).slice(2)),
  )
}
