name: "Setup fd-find"
description: "Setup fd-find"
inputs:
  fd-find-version:
    description: "fd-find version"
    required: true
    default: "8.4.0"
runs:
  using: "composite"
  steps:
    - name: Cache fd-find
      uses: actions/cache@v3
      id: cache-fd-find
      with:
        path: |
          /usr/local/bin/fd
        key: fd-find-test-${{ inputs.fd-find-version }}
    - if: ${{ steps.cache-fd-find.outputs.cache-hit != 'true' }}
      name: Install fd-find
      run: |
        cargo install --version ${{ inputs.fd-find-version }} fd-find
        cp ~/.cargo/bin/fd /usr/local/bin/fd
      shell: bash
