import { chain as kusama } from "kusama/mod.ts"
import { chain as polkadot } from "polkadot/mod.ts"
import { chain as rococo } from "rococo/mod.ts"
import { chain as westend } from "westend/mod.ts"
import { emptyDir } from "../deps/std/fs.ts"
import dprintConfig from "../dprint.json" assert { type: "json" }
import { hex } from "../util/mod.ts"

const GENERATION_NOTICE = `// This file was generated by \`_tasks/downloads.ts\``

const response = await fetch(
  dprintConfig.plugins.find((v) => v.startsWith("https://plugins.dprint.dev/typescript-"))!,
)
const wasm = new TextDecoder().decode(hex.encodeBuf(new Uint8Array(await response.arrayBuffer())))
const tsFormatterPath = new URL("../util/tsFormatter.ts", import.meta.url)
await Deno.writeTextFile(
  tsFormatterPath,
  `${GENERATION_NOTICE}
import { createFromBuffer } from "../deps/dprint.ts"
import dprintConfig from "../dprint.json" assert { type: "json" }
import { decode } from "./hex.ts"

const wasm = "${wasm}"

export const tsFormatter = createFromBuffer(decode(wasm))
const { indentWidth, lineWidth, typescript: config } = dprintConfig
tsFormatter.setConfig({ indentWidth, lineWidth }, config)
`,
)
if (true as boolean) Deno.exit()

const knownChains = { kusama, polkadot, westend, rococo }
const names = Object.keys(knownChains)
const outDir = new URL("../frame_metadata/_downloaded", import.meta.url)
await emptyDir(outDir)

const modFilePath = new URL("_downloaded/mod.ts", outDir)
const modFileContents = `${GENERATION_NOTICE}
import { hex } from "../../util/mod.ts"
import { $metadata } from "../mod.ts"

export const [
  ${names.join(",\n  ")},
] = await Promise.all([
  ${names.map((name) => `download("${name}")`).join(",\n  ")},
])

async function download(name: string) {
  return $metadata.decode(
    hex.decodeBuf((await Deno.readFile(new URL(\`./$\{name}.scale\`, import.meta.url))).slice(2)),
  )
}
`
Deno.writeTextFileSync(modFilePath, modFileContents, { create: true })

await Promise.all(
  Object.entries(knownChains).map(async ([name, chain]) => {
    const result = await chain.connection.call("state_getMetadata").run()
    const outPath = new URL(`_downloaded/${name}.scale`, outDir)
    console.log(`Downloading ${name} metadata to "${outPath}".`)
    await Deno.writeTextFile(outPath, result)
  }),
)
