import { hex } from "../crypto/mod.ts"
import dprintConfig from "../dprint.json" assert { type: "json" }

const GENERATION_NOTICE = `// This file was generated by \`_tasks/downloads.ts\``

const response = await fetch(
  dprintConfig.plugins.find((v) => v.startsWith("https://plugins.dprint.dev/typescript-"))!,
)
const wasm = new TextDecoder().decode(hex.encodeBuf(new Uint8Array(await response.arrayBuffer())))
const tsFormatterPath = new URL("../util/tsFormatter.ts", import.meta.url)
await Deno.writeTextFile(
  tsFormatterPath,
  `${GENERATION_NOTICE}
import { createFromBuffer } from "../deps/dprint.ts"
import dprintConfig from "../dprint.json" assert { type: "json" }
import { hex } from "../crypto/mod.ts"

const wasm = "${wasm}"

export const tsFormatter = createFromBuffer(hex.decode(wasm))
const { indentWidth, lineWidth, typescript: config } = dprintConfig
tsFormatter.setConfig({ indentWidth, lineWidth }, config)
`,
)
