name: Checks
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  CAPI_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@2f1cf31537886c3bfb05591c031f7744e48ba8a1 # v2.2

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - run: deno lint

  spellcheck:
    name: Spelling
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@6eb87310ae9cb344fb342ea01a2f74979fb31b86 # v2.7.0

  cache:
    name: Cache
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/await_deployment.ts
        timeout-minutes: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task run _tasks/star.ts
      - run: deno cache target/star.ts || deno cache target/star.ts || deno cache target/star.ts

  sync:
    name: Sync
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - run: deno task sync --check

  star:
    name: Star
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task run _tasks/star.ts
      - run: deno task cache target/star.ts
      - run: deno task check target/star.ts

  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task test

  examples-deno:
    name: Examples (Deno)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task test:examples:deno
