name: Check Secrets
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
