name: Checks
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  CAPI_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@2f1cf31537886c3bfb05591c031f7744e48ba8a1 # v2.2

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - run: deno lint

  spellcheck:
    name: Spelling
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@c5eae96241f654d2437c16bdfad146ff33a025cc # v2.7.0

  cache:
    name: Cache
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/await_deployment.ts
        timeout-minutes: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task run _tasks/star.ts
      # Attempt caching many times; #856
      - run: deno cache target/star.ts || deno cache target/star.ts || deno cache target/star.ts || deno cache target/star.ts || deno cache target/star.ts || deno cache target/star.ts
      - name: Archive target
        uses: actions/upload-artifact@v3
        if: failure() || cancelled()
        with:
          name: cache-target
          path: |
            target
            !target/**/db/full/*
            !target/**/paritydb/full/*

  sync:
    name: Sync
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - run: deno task sync --check
      - name: Archive target
        uses: actions/upload-artifact@v3
        if: failure() || cancelled()
        with:
          name: sync-target
          path: |
            target
            !target/**/db/full/*
            !target/**/paritydb/full/*

  star:
    name: Star
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task run _tasks/star.ts
      - run: deno task cache target/star.ts
      - run: deno task check target/star.ts

  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task test

  examples-deno:
    name: Examples (Deno)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task test:eg:deno
      - name: Archive target
        uses: actions/upload-artifact@v3
        if: failure() || cancelled()
        with:
          name: examples-deno-target
          path: |
            target
            !target/**/db/full/*
            !target/**/paritydb/full/*

  examples-node:
    name: Examples (Node)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.0
        with:
          deno-version: v1.33.3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ env.CAPI_SHA }}
      - run: deno run -A _tasks/use_remote.ts
      - run: deno task dnt --server ${{ env.CAPI_SHA }} --examples
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: deno task test:eg:node
      - name: Archive target
        uses: actions/upload-artifact@v3
        if: failure() || cancelled()
        with:
          name: examples-node-target
          path: |
            target
            !target/**/db/full/*
            !target/**/paritydb/full/*
