name: Configure Labels
on:
  push:
    paths:
      - ".github/labels.yml"
    branches:
      - main
jobs:
  configure:
    name: Configure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
