name: Dev Container Builds
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.2
        with:
          push: never
          runCmd: deno task star
