name: Examples

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
    uses: ./.github/actions/troodontid
    with:
      dir: examples
