name: Examples (Deno)

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      # - run: deno run -A _tasks/validate_ignore.ts --dir examples
      - uses: ./.github/actions/troodontid
        with:
          dir: examples
          importMap: import_map.json
          concurrency: 1
