name: Examples (Browser)

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ghcr.io/paritytech/trun:main
    steps:
      - uses: actions/checkout@v3
      - run: deno task capi -- deno run -A -r=http://localhost:4646/ /trun/main.ts --dir examples --import-map import_map.json --concurrency 1 --reload http://localhost:4646/ --browser
