name: Examples

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/troodontid
        with:
          dir: examples
          importMap: import_map.json
