name: Examples

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          ref: "master"
      - name: Run the private action
        uses: ../troodontid
        with:
          dir: "examples"
