name: Secrets check
on:
  pull_request:
    types:
      - created
      - edited
jobs:
  echo_issue_comment:
    runs-on: ubuntu-latest
    name: secrets check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.10.3
