name: Spawn Examples
on:
  - workflow_dispatch
  - push
  - pull_request
jobs:
  generate_example_paths:
    name: Generate example paths
    runs-on: ubuntu-latest
    outputs:
      example_paths: ${{ steps.generate_example_paths.outputs.example_paths }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup fd-find
        uses: ./.github/actions/setup-fd-find
      - id: generate_example_paths
        run: |
          fd --print0 --glob "*.ts" ./examples | jq -Rnc '(input | split("\u0000"))' > example_paths.json
          example_paths=`cat example_paths.json`
          echo "example_paths=$example_paths" >> $GITHUB_OUTPUT
  run_example_workflow:
    needs: generate_example_paths
    name: Run examples
    uses: ./.github/workflows/example.yml
    with:
      example_paths: ${{ needs.generate_example_paths.outputs.example_paths }}
