name: Spawn examples
on:
  workflow_dispatch:
  push:
jobs:
  spawn_examples:
    name: Spawn examples
    runs-on: ubuntu-latest
    outputs:
      example_paths: ${{ steps.generate_examples.outputs.example_paths }}
    steps:
      - uses: actions/checkout@v3
      - id: generate_examples
        run: |
          find ./examples -type f -print0 | jq -Rnc '(input | split("\u0000"))' > example_paths.json
          example_paths=`cat example_paths.json`
          echo "example_paths=$example_paths" >> $GITHUB_OUTPUT

  call_example_workflow:
    needs: spawn_examples
    uses: ./.github/workflows/example.yml
    with:
      example_paths: ${{ needs.spawn_examples.outputs.example_paths }}
