name: Spellcheck
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@236a257d503bd664697d2f33afc007ccc3a53f80 # v2.7.0
