name: "Check Spelling"
on: push
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@6b6ac0b399a30dbd13f28c6bae1ef4ee5f4e8905 # v2.7.0
