name: "Check Spelling"
on: push
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@12ae7d0a178b8b1f95343b7a6f79df04ff8dde0e # v2.7.0
