name: "Check Spelling"
on: push
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@b88ea4a807ea2d641cebf2a52f667038015ad711 # v2.7.0
