name: Spellcheck
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@2efa70d4910d487d2ac22513b8c9e4f4ad76fddb # v2.7.0
