name: Spellcheck
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@faedcf94dee84afad3966c3ca108a0650b0e6c5e # v2.7.0
