name: Spellcheck
on:
  - pull_request
  - push
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@d7f4191619d5455523f0fd625ce1a983f9ce5ccb # v2.7.0
