name: Spellcheck
on: push
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@f289d32d6267fbb1d23fb8e4b66905fc7c63cac4 # v2.7.0
