name: Star
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
jobs:
  star:
    name: Star
    runs-on: ubuntu-latest
    timeout-minutes: 30 # :(
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deps/**/*.ts') }}
      - name: Setup Binaries
        uses: ./.github/actions/setup-binaries
      - run: deno task star
