name: Star
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
jobs:
  star:
    name: Star
    runs-on: ubuntu-latest
    timeout-minutes: 30 # :(
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deps/**/*.ts') }}
      - name: Setup Polkadot
        uses: ./.github/actions/setup-binary
        with:
          binary-name: polkadot
          binary-version: v0.9.37
          binary-github: https://github.com/paritytech/polkadot
      - name: Setup Cumulus
        uses: ./.github/actions/setup-binary
        with:
          binary-name: polkadot-parachain
          binary-version: v0.9.370
          binary-github: https://github.com/paritytech/cumulus
      - name: Setup Zombienet
        uses: ./.github/actions/setup-binary
        with:
          binary-name: zombienet-linux-x64
          binary-version: v1.3.34
          binary-github: https://github.com/paritytech/zombienet
      - run: deno task star
