name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.0
        with:
          deno-version: v1.x
      - name: Setup polkadot
        uses: ./.github/actions/setup-polkadot
      - run: deno lint
      - run: deno task codegen
      - run: deno task star
      - run: deno task test
      - run: deno task test:examples
